#!/bin/bash  -e



: ' basic commands 
by parivallal 
on 23.02.2019 '

cat documents | while read line;do git add .;read -p "Commit description: " desc  ;git commit -m $desc;git push origin master ;done
