#!/bin/bash  -e

: 'scripting 
by parivallal
on 10.02.2019 '

for x in {1..5};do cp first.txt first$x.c;sed -i 's/Devops/${x}/g' first$x.c;git add first$x.c;git commit -m "name$x.c";git pull origin master;git push origin master;done
